sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

notifications:
  email: false

before_install:
  - npm i -g npm

before_script:
  - npm prune

script:
  - npm test
  - npm run coverage

after_success:
  - npm run coverage:upload
  - npm run semantic-release
